modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/Awakened-Redstone/SakuraCake/issues"
license = "GPL-3.0"

[[mods]]
modId = "sakuracake"
version = "${version}"
displayName = "${mod_name}"
authors = "Awakened Redstone"
description = '''
${description}
'''
logoFile = "assets/${mod_id}/icon.png"

[[mixins]]
config = "sakuracake.mixins.json"

[[mixins]]
config = "sakuracake-client.mixins.json"

[[mixins]]
config = "sakuracake-compat.mixins.json"

[[dependencies.sakuracake]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"

[[dependencies.sakuracake]]
modId = "fabric_api"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.sakuracake]]
modId = "embeddium"
type = "incompatible"
versionRange = "*"
reason="Incompatible, use sodium 0.6 instead"

[[dependencies.sakuracake]]
modId = "sodium"
type = "discouraged"
versionRange = "[,0.6-beta)"
reason="Agressive culling, use sodium 0.6 instead"
